### ISSUE TITLE
Problem with parsing prequisite names?

### ISSUE THREAD

**Issue by rrthomas** [gvvaughan/bootstrap#2]
I added the following line to my `bootstrap.conf`'s `buildreq` section:

```
buildreq='
        pkg-config -       https://www.freedesktop.org/wiki/Software/pkg-config/
'
```

and get the error:

```
bootstrap:   error: Prerequisite 'CONFIG-pkg-config' not not found. Please install it, or
bootstrap:          'export PKG-CONFIG=/path/to/CONFIG-pkg-config'.
```

Looks like something has gone wrong with parsing `pkg-config`?

**Comment by gvvaughan** [comment]
Hey Reuben!

Does this reproduce on the active fork repo? https://github.com/gnulib-modules/bootstrap. If so, can you refile the report there, please?
